### ISSUE TITLE
It does not seem to work with webpack 2.1.0-beta.25 and webpack-dev-server

### ISSUE THREAD

**Issue by jusefb** [AngularClass/angular2-hmr#31]
I have followed the example setup but I am getting the following error where running the webpack-dev-server: 

```
....
ERROR in [default] ...\app.module.ts:8:54 
Property 'metadata' does not exist on type 'typeof Reflect'.

ERROR in [default] ....\app.module.ts:8:94 
Property 'metadata' does not exist on type 'typeof Reflect'.

ERROR in [default] ....\app.module.ts:67:4 
Invalid left-hand side of assignment expression.

Argument of type '(appRef: any) => void' is not assignable to parameter of type 'Type<{}>'.
  Type '(appRef: any) => void' provides no match for the signature 'new (...args: any[]): {}'
```

Any ideas?

**Comment by gdi2290** [comment]
thanks, the latest release removes the peer dep
